- name: Add docker apt signing key with URL
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install containerd
  apt: 
    name: containerd.io=1.6.14-1
    state: present
    update_cache: yes

- name: Configure containerd
  block: 
  - name: Create directory /etc/containerd
    shell: sudo mkdir -p /etc/containerd
  - name: Add containerd conf file
    shell: sudo containerd config default | sudo tee /etc/containerd/config.toml
  notify: Restart containerd

- name: Flush handlers
  meta: flush_handlers