- block:
    - name: Initialize the cluster
      shell: kubeadm init --pod-network-cidr=172.16.40.0/23
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: Create .kube directory
      become_user: kube
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/kube/.kube/config
        remote_src: yes
        owner: kube

    - name: Install Pod network
      become_user: kube
      shell: kubectl apply -f {{ network_provider }} 
      args:
        chdir: $HOME
        
    - name: Get the token for joining the worker nodes
      become_user: kube
      shell: kubeadm token create --print-join-command
      register: kubernetes_join_command

    - debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to file.
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
  when: "'master' in ansible_nodename"
