# - name: Update the /etc/hosts file with node name and IP
#   tags: etchostsupdate
#   lineinfile:
#     path: "/etc/hosts"
#     regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
#     line: "{{ hostvars[item].ansible_default_ipv4.address }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
#     state: present
#     backup: yes
#   register: etchostsupdate
#   when: ansible_hostname != "{{ item }}" or ansible_hostname == "{{ item }}"
#   with_items: "{{groups['all']}}"

- name: Updating linux hosts file
  copy:
    src: /home/leonardo/terraform/proxmox/lab-kubernetes/hosts
    dest: /etc/hosts